### ISSUE TITLE
Error when constructing and dropping multiple `OCamlRuntime`s

### ISSUE THREAD

**Issue by abrown** [tezedge/ocaml-interop#35]
I believe the following code will fail:

```
   enum Value { ... }

    fn foo(v: Value) {
        let ocaml_runtime = &mut OCamlRuntime::init();
        let v = v.to_boxroot(ocaml_runtime);
    }

    #[test]
    fn run_foo_multiple_times() {
        foo(Value::I32(42));
        foo(Value::I32(43));
    }
```

```
running 1 test
boxroot is not setup
error: test failed, to rerun pass '-p ... --lib'

Caused by:
  process didn't exit successfully: `...-adda821b531633ed 'tests::run_foo_multiple_times' --exact --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
```

I suspect that `Drop` for `OCamlRuntime` is running `boxroot_teardown` but the equivalent `boxroot_setup` is not being called when the new runtime is constructed?

**Comment by tizoc** [comment]
Hello @abrown. The Drop is indeed the issue, but it is just not about boxroots: https://ocaml.org/manual/intfc.html#sec466

> Once a runtime is unloaded, it cannot be started up again without reloading the shared library and reinitializing its static data. Therefore, at the moment, the facility is only useful for building reloadable shared libraries.

If you are writing tests, use instead a combination of `OCamlRuntime::init_persistent` and `OCamlRuntime::recover_handle`: https://github.com/tezedge/ocaml-interop/blob/fefebda5f040b3ae3bf57e6e9773dbccda256d98/testing/rust-caller/src/lib.rs#L161

**Comment by abrown** [comment]
Ah, interesting, thanks for pointing out that link. What I'm actually doing is running an [interpreter](https://github.com/WebAssembly/spec/tree/master/interpreter) written in OCaml from Rust using a function like `fn interpret(module: &[u8], params: Vec<Value>) -> Vec<Value>`; I assumed it would be safer to restart the `OCamlRuntime` every time in hopes that any mistakes/hacks in the OCaml code will not interfere with back-to-back calls to `interpret`. You've shown me this will not work in a single process (a requirement) so it seems like I can try the `OCamlRuntime::init_persistent/OCamlRuntime::recover_handle` route, which means I just have to end up trusting the OCaml code, right? Would you recommend some other way? Or what should I be looking for on the OCaml side to audit that back-to-back calls will not interfere? (I mean, I suspect that there is little (?) mutable state on the OCaml side but is there something else I need to worry about?)

**Comment by tizoc** [comment]
@abrown it would depend on the OCaml code. What worries you is possible mistakes, not that the OCaml code comes from an untrusted source, right?

I am not very familiar with WASM, so I don't know what can be the effects of running WASM code (and I guess it also depends on the interpreter). 

Let's say the interpreter has some global state (it's own, without doing weird stuff with the OCaml runtime), you can probably expose some function to reset that global state when you need to do so. As long as it doesn't do anything with the OCaml runtime (like change GC settings, load dynamic libraries, call C code that has its own global state, etc), then I guess there shouldn't be any issue. You should then initialize the OCaml runtime once and not worry about it in that case.

Using multiple processes is the easy solution, but if working with a single-process is a requirement, that is not an option.

**Comment by abrown** [comment]
> What worries you is possible mistakes, not that the OCaml code comes from an untrusted source, right?

Right.

> (like change GC settings, load dynamic libraries, call C code that has its own global state, etc)

Ok, I'll hunt around for stuff like that but I'm pretty sure I won't find any. I'm also relatively confident that the functional style the interpreter is written in avoids most mutable state (e.g. I think instantiating a module anew should provide a completely new state) but I'll just make sure. 

Thanks for the help! And thanks for maintaining a nice library!
